import unittest

from unit_tests_collisions import TestCollisions
from unit_tests_robots_3_spheres import TestRobotsDistanceDerivativesSpheres
from unit_tests_robots_3_capsules import TestRobotsDistanceDerivativesCapsules
from unit_tests_robots_1capsule_2spheres import TestRobotsDistanceDerivativesCapsuleSpheres

unittest.main()
