pull_request_rules:
  - name: merge auto PRs when CI is OK
    conditions:
      - check-success = "build"
      - check-success = "nix (macos)"
      - check-success = "nix (ubuntu)"
      - check-success = "pre-commit.ci - pr"
      - or:
        - author = dependabot[bot]
        - author = github-actions[bot]
        - author = hrp2-14
        - author = pre-commit-ci[bot]
    actions:
      merge:
