---
name: Build Colmpc Image
on:
  workflow_run:
    workflows: ["Build Base Image"]
    types:
      - completed
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set env with tag
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          export RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "DOCKER_TAGS="colmpc:$RELEASE_VERSION, colmpc:latest"" >> $GITHUB_ENV
          echo "BASE_IMAGE="colmpc:base-$RELEASE_VERSION, colmpc:base-latest"" >> $GITHUB_ENV
      - name: Set env with tag
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo "RELEASE_VERSION=""" >> $GITHUB_ENV
          echo "DOCKER_TAGS="colmpc:latest"" >> $GITHUB_ENV
          echo "BASE_IMAGE="colmpc:base-latest"" >> $GITHUB_ENV

      - name: Build Docker with colmpc and test the implementation
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/colmpc.Dockerfile
          tags: ${{ env.DOCKER_TAGS }}
          build-args: COLMPC_COMMIT_HASH=$GITHUB_SHA, BASE_IMAGE=$BASE_IMAGE, MAKE_JOBS=4
          push: false

      - name: Login to GitHub Container Registry
        # Push the latest image to registry only if running on main
        if: ${{ (github.ref == 'refs/heads/main') || startsWith(github.event.ref, 'refs/tags/v') }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v6
        if: ${{ (github.ref == 'refs/heads/main') || startsWith(github.event.ref, 'refs/tags/v') }}
        with:
          tags: ${{ env.DOCKER_TAGS }}
          push: true
