---
name: Build Colmpc Image
on:
  workflow_run:
    workflows: ["Build Base Image"]
    types:
      - completed
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set env with Docker prefix
        run: echo "DOCKER_PREFIX="ghcr.io/${{ github.repository_owner }}"" >> $GITHUB_ENV

      - name: Set env with tag
        if: ${{ (github.event_name == 'workflow_run') && startsWith(github.event.workflow_run.head_branch, 'refs/tags/v') }}
        run: |
          export WORKFLOW_HEAD_BRANCH=${{  github.event.workflow_run.head_branch }}
          export REL_VER=${WORKFLOW_HEAD_BRANCH#refs/tags/}
          echo "DOCKER_TAGS="$DOCKER_PREFIX/colmpc:$REL_VER, $DOCKER_PREFIX/colmpc:latest"" >> $GITHUB_ENV
          echo "BASE_IMAGE="$DOCKER_PREFIX/base-$REL_VER"" >> $GITHUB_ENV
          echo "COLMPC_COMMIT_HASH="$REL_VER"" >> $GITHUB_ENV

      - name: Set env with tag
        if: ${{ github.event_name != 'workflow_run' || !startsWith(github.event.workflow_run.head_branch, 'refs/tags/v') }}
        run: |
          echo "DOCKER_TAGS="$DOCKER_PREFIX/colmpc:latest"" >> $GITHUB_ENV
          echo "BASE_IMAGE="$DOCKER_PREFIX/base-latest"" >> $GITHUB_ENV
          echo "COLMPC_COMMIT_HASH="$GITHUB_SHA"" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        # Push the latest image to registry only if running on main
        if: ${{ (github.ref == 'refs/heads/main') || startsWith(github.event.ref, 'refs/tags/v') }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker with colmpc and test the implementation
        if: ${{ (github.ref != 'refs/heads/main') && !startsWith(github.event.ref, 'refs/tags/v') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/colmpc.Dockerfile
          tags: ${{ env.DOCKER_TAGS }}
          build-args: COLMPC_COMMIT_HASH=$COLMPC_COMMIT_HASH, BASE_IMAGE=$BASE_IMAGE, MAKE_JOBS=4
          push: false

      - name: Build and Push Docker with colmpc and test the implementation
        if: ${{ (github.ref == 'refs/heads/main') || startsWith(github.event.ref, 'refs/tags/v') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/colmpc.Dockerfile
          tags: ${{ env.DOCKER_TAGS }}
          build-args: COLMPC_COMMIT_HASH=$GITHUB_SHA, BASE_IMAGE=$BASE_IMAGE, MAKE_JOBS=4
          push: true
